# Scrapping data from Makaan.com

In [3]:
#importing required packages

import requests
from bs4 import BeautifulSoup
import pandas as pd
import time
from IPython.display import clear_output

In [4]:
owner_info=[]
no_BHK=[]
constr=[]
Ar=[]
loc=[]
Cost=[]
pr_per_sqft = []

base_url='https://www.makaan.com/hyderabad-residential-property/buy-property-in-hyderabad-city?_=1624536394722'

for i in range(1,51):
    
    time.sleep(3)
    print(f'Scrapping for page {i}')
    clear_output(wait=True)
    
    
    url=base_url+'&page='+str(i)
    req=requests.get(url)
    soup=BeautifulSoup(req.text,'html')
    
    #bhk info
    bhk_inf=soup.findAll('div',attrs={'class':'title-line'})
    for j in bhk_inf:
        no_BHK.append(j.strong.span.text)
    
    #location info
    loc_inf=soup.findAll('span',attrs={'itemprop':'addressLocality'})
    for k in loc_inf:
        loc.append(k.text)
    
    #owner_info
    own_inf=soup.findAll('span',attrs={'class':'seller-type'})
    for l in own_inf:
        owner_info.append(l.text)
    
    #price
    price=soup.findAll('div',attrs={'data-type':'price-link'})
    for m in price:
        Cost.append(m.text)
    
    #Area in sqft
    area=soup.findAll('td',attrs={'class':'size'})
    for n in area:
        Ar.append(n.span.text.strip())
        
    #construction status
    con_inf=soup.findAll('td',attrs={'class':'val'})
    for o in con_inf:
        constr.append(o.text)
        
    #price per sqft
    pps_info = soup.findAll('td',attrs={'class':'lbl rate'})
    for p in pps_info:
        pr_per_sqft.append(p.text)

Scrapping for page 50

In [5]:
#creating Data Frame

datas=pd.DataFrame({'Construction':constr,
                  'Area_in_Sqft':Ar,
                  'Price':Cost,
                  'Owner_info':owner_info,
                  'Locality':loc,
                  'BHK':no_BHK,
                  'Price_per_sqft':pr_per_sqft})
datas

,Construction,Area_in_Sqft,Price,Owner_info,Locality,BHK,Price_per_sqft
0,Under Construction,2810,1.6 Cr,BUILDER,Manikonda,3,"5,699 / sq ft"
1,Ready to move,1495,1.43 Cr,BUILDER,Shaikpet,2,"9,565 / sq ft"
2,Under Construction,1295,56.98 L,BUILDER,Bachupally,2,"4,400 / sq ft"
3,Under Construction,890,43.6 L,BUILDER,Shamshabad,2,"4,899 / sq ft"
4,Under Construction,1431,65.82 L,BUILDER,Tellapur,3,"4,600 / sq ft"
...,...,...,...,...,...,...,...
995,Resale,2403,18.69 L,OWNER,Kadthal,Residential Plot,777 / sq ft
996,Under Construction,1195,49 L,OWNER,Bolarum,2,"4,100 / sq ft"
997,Ready to move,1300,67 L,OWNER,Rampally,2,"5,153 / sq ft"
998,Ready to move,1050,60 L,OWNER,Hayathnagar,2,"5,714 / sq ft"
999,Resale,900,3.5 L,OWNER,Shamshabad,Residential Plot,388 / sq ft

In [6]:
# saving file with .csv extension
datas.to_csv('Makaan_scrapped_data.csv',index=False)